#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N density_vector1
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422163905121422vcDFQj/pbs/density_vector1.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422163905121422vcDFQj/pbs/density_vector1.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python density_vector.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422163905121422vcDFQj/para 1
