#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N density0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304091446178148975XksXx/pbs/density0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304091446178148975XksXx/pbs/density0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python density.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304091446178148975XksXx/para 0
