#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default

export LD_LIBRARY_PATH=/export/apps/compilers/gcc48/lib64

#PBS -N stero0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130718140743155199axLlVa/pbs/sterol_tilt_ring0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130718140743155199axLlVa/pbs/sterol_tilt_ring0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/export/apps/bin/python2.7 sterol_tilt_ring.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130718140743155199axLlVa/para 0
