#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt_sub3
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130113156567166zN1FjC/pbs/helix_tilt_sub3.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130113156567166zN1FjC/pbs/helix_tilt_sub3.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130113156567166zN1FjC/para 3
