#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N density3
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130417155546625899BkZm9Y/pbs/density3.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130417155546625899BkZm9Y/pbs/density3.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python density.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130417155546625899BkZm9Y/para 3
