#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N order_parameter0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130430161112303153k797Pz/pbs/order_parameter0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130430161112303153k797Pz/pbs/order_parameter0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python order_parameter.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130430161112303153k797Pz/para 0
