#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt30
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212135022242593tVJDbu/pbs/helix_tilt30.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212135022242593tVJDbu/pbs/helix_tilt30.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212135022242593tVJDbu/para 30
