#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l pcput=72:00:00
#PBS -q default
#PBS -N densi0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131016155203522768UcixHi/pbs/density_waterdp0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131016155203522768UcixHi/pbs/density_waterdp0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/export/apps/bin/python2.7 density_waterdp.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131016155203522768UcixHi/para 0
