#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N helix0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130603125526288909d6WHCV/pbs/helix_tilt0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130603125526288909d6WHCV/pbs/helix_tilt0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130603125526288909d6WHCV/para 0
