#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt_sub16
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302121335439526451FfZph/pbs/helix_tilt_sub16.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302121335439526451FfZph/pbs/helix_tilt_sub16.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302121335439526451FfZph/para 16
