#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N lipid0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130703113724469076Q3a79V/pbs/lipid_per_area_dela0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130703113724469076Q3a79V/pbs/lipid_per_area_dela0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python lipid_per_area_dela.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130703113724469076Q3a79V/para 0
