#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N box1
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302201646339530829qrSaX/pbs/box1.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302201646339530829qrSaX/pbs/box1.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python box.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201302201646339530829qrSaX/para 1
