#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N thick0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531165347853310a9E5tA/pbs/thickness_carbon0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531165347853310a9E5tA/pbs/thickness_carbon0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python thickness_carbon.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531165347853310a9E5tA/para 0
