#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N density0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130325163332341499Zq2w6a/pbs/density0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130325163332341499Zq2w6a/pbs/density0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python density.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130325163332341499Zq2w6a/para 0
