#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt2
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130214094846323309dOcptN/pbs/helix_tilt2.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130214094846323309dOcptN/pbs/helix_tilt2.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130214094846323309dOcptN/para 2
