#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt10
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212134715672011ZA3ayO/pbs/helix_tilt10.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212134715672011ZA3ayO/pbs/helix_tilt10.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130212134715672011ZA3ayO/para 10
