#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N ordpara_dopc0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/2013050214083401184524KB38/pbs/ordpara_dopc0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/2013050214083401184524KB38/pbs/ordpara_dopc0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python ordpara_dopc.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/2013050214083401184524KB38/para 0
