#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N thick0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531164727703001ax1bJB/pbs/thickness_phosphate0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531164727703001ax1bJB/pbs/thickness_phosphate0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python thickness_phosphate.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130531164727703001ax1bJB/para 0
