#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N box0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/pbs/box0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/pbs/box0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python box.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/para 0
