#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt1
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/pbs/helix_tilt1.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/pbs/helix_tilt1.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130213143238258419aIY1hU/para 1
