#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N box
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130111161800680160SvjX34/pbs/box.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130111161800680160SvjX34/pbs/box.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python box.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130111161800680160SvjX34/para
