#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=720:00:00
#PBS -l pcput=720:00:00
#PBS -q grammx
#PBS -N area_0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131007162854654145RaYTaU/pbs/area_per_lipid0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131007162854654145RaYTaU/pbs/area_per_lipid0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/export/apps/bin/python2.7 area_per_lipid.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131007162854654145RaYTaU/para 0
