#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N vector_selection0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130425101233470582gx5ixy/pbs/vector_selection0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130425101233470582gx5ixy/pbs/vector_selection0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python vector_selection.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130425101233470582gx5ixy/para 0
