#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default

export LD_LIBRARY_PATH=/export/apps/compilers/gcc48/lib64

#PBS -N vecto0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130821103558266744HYbYYk/pbs/vector_selection0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130821103558266744HYbYYk/pbs/vector_selection0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/export/apps/bin/python2.7 vector_selection.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130821103558266744HYbYYk/para 0
