#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt_sub4
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114345799704c5vWCV/pbs/helix_tilt_sub4.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114345799704c5vWCV/pbs/helix_tilt_sub4.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114345799704c5vWCV/para 4
