#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l pcput=72:00:00
#PBS -q default
#PBS -N stero0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131004151647039945Oku33p/pbs/sterol_tilt_tail0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131004151647039945Oku33p/pbs/sterol_tilt_tail0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/export/apps/bin/python2.7 sterol_tilt_tail.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20131004151647039945Oku33p/para 0
