#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt_sub6
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114748557743mcRJqZ/pbs/helix_tilt_sub6.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114748557743mcRJqZ/pbs/helix_tilt_sub6.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114748557743mcRJqZ/para 6
