#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N density_vector0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422161052309722d5io2z/pbs/density_vector0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422161052309722d5io2z/pbs/density_vector0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python density_vector.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130422161052309722d5io2z/para 0
