#!/bin/csh
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q default
#PBS -N helix_tilt_sub0
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114928226113Jt0rJ0/pbs/helix_tilt_sub0.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114928226113Jt0rJ0/pbs/helix_tilt_sub0.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
/home/sunhwan/local/python/bin/python helix_tilt.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/20130130114928226113Jt0rJ0/para 0
