#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l mem=500mb
#PBS -l walltime=72:00:00
#PBS -l cput=72:00:00
#PBS -q charmm_nmr
#PBS -N density2
#PBS -e /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304171507392529886o0cSl/pbs/density2.err
#PBS -o /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304171507392529886o0cSl/pbs/density2.log
cd /home2/jcjeong/project/stanalyzer0/stanalyzer/static/analyzers
python density.py /home2/jcjeong/project/stanalyzer0/stanalyzer/media/jcjeong/201304171507392529886o0cSl/para 2
